apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-api

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: pf-devops-cloud
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/USUARIO/task-api
    newTag: latest
